import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { twMerge } from 'tailwind-merge'
import { SpeedInsights } from '@vercel/speed-insights/next'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<head>
			<title>Thomas van Rijn</title>
			<meta name={'viewport'} content={'width=device-width, initial-scale=1.0'}/>
		</head>
		<body className={twMerge(inter.className, 'bg-gray-950 bg-cover bg-center')}
			  style={{ backgroundImage: 'url(img/bg.png)' }}>
		<SpeedInsights/>
		{children}
		</body>
		</html>
	)
}
